version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache-assessment2
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpeg-api-assessment2
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-cab432-n11538082-videos}
      - COGNITO_CLIENT_ID=1m661s6635scnkirlsjgl7hmb8
      - RDS_PORT=5432
      - RDS_USERNAME=s323
      - RDS_PASSWORD=vNo7jHx2HU1q
      - RDS_HOSTNAME=database-1-instance-1.ce2haupt2cta.ap-southeast-2.rds.amazonaws.com
      - RDS_DB_NAME=cohort_2025
      - REDIS_URL=redis://redis:6379
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - ASSESSMENT_MODE=assessment2
      - STUDENT_ID=${STUDENT_ID}
      - ENABLE_DEBUG_LOGGING=true
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
    name: assessment2-network
