version: '3.8'
services:
  memcached:
    image: memcached:1.6-alpine
    container_name: memcached-cache-assessment2
    ports:
      - "11211:11211"
    command: memcached -m 64 -vv
    networks:
      - app-network
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpeg-api-assessment2
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-cab432-n11538082-videos}
      - COGNITO_USER_POOL_ID=ap-southeast-2_rrPRQJFkU
      - COGNITO_CLIENT_ID=1m661s66355cnkirlsjgl7hmb8
    #  - COGNITO_CLIENT_SECRET=1nq1s8kkt0pg0fr1q10saq1r1o2nqth794id3rp86gkttiejphri
      - RDS_PORT=5432
      - RDS_USERNAME=s323
      - RDS_PASSWORD=vNo7jHx2HU1q
      - RDS_HOSTNAME=database-1-instance-1.ce2haupt2cta.ap-southeast-2.rds.amazonaws.com
      - RDS_DB_NAME=cohort_2025
      - MEMCACHED_URL=a2-allen-dante.km2jzi.cfg.apse2.cache.amazonaws.com:11211
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - ASSESSMENT_MODE=assessment2
      - STUDENT_ID=n11538082
      - ENABLE_DEBUG_LOGGING=true
    restart: unless-stopped
    depends_on:
      - memcached
    networks:
      - app-network
volumes:
  postgres_data:
    driver: local
networks:
  app-network:
    driver: bridge
    name: assessment2-network
